# Generated by Django 4.0 on 2021-12-26 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clantournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentarticlemodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
