# Generated by Django 4.0 on 2021-12-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clantournament', '0002_tournamentarticlemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentarticlemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
