# Generated by Django 4.0 on 2021-12-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clantournament', '0003_alter_tournamentarticlemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentarticlemodel',
            name='hold_flag',
            field=models.BooleanField(default=False),
        ),
    ]
