# Generated by Django 4.0 on 2021-12-24 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_remove_clanusermodel_topimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanusermodel',
            name='position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
    ]
