# Generated by Django 4.0 on 2021-12-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_remove_clanusermodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanusermodel',
            name='position',
            field=models.CharField(choices=[('0', 'リーダー'), ('1', 'サブリーダー'), ('2', '長老'), ('3', 'メンバー')], default='3', max_length=50),
            preserve_default=False,
        ),
    ]
